
##########################################################################
## MAKEFILE: DEBUGGER TEMPLATE      					                ##
##########################################################################
HDIR		:= hdr
SDIR		:= src
ODIR		:= obj

EXET		:= a
OBJS		:= main.o testDebugger.o
OSRC		:= $(addprefix $(ODIR)/, $(OBJS))
